server:
  external_dns: "1.1.1.1"
  listen_addr: "0.0.0.0"
  listen_port: 53
  allowed_ips:
    - "10.0.0.0/24"
    - "127.0.0.0/8"

cache:
  redis_host: "127.0.0.1:6379"
  password: ""
  database: 0
  max_retries: 2
  timeout_sec: 2

private_domains:
  home:
    gw: "10.0.0.1"